### ISSUE TITLE
Building for M1

### ISSUE THREAD

**Issue by esphynox** [SDWebImage/libde265-Xcode#4]
Compilation fails for Apple Silicon processor.

Error:

<img width="740" alt="Screenshot 2021-11-19 at 14 26 37" src="https://user-images.githubusercontent.com/8351932/142622762-51d149c0-60cb-4381-a066-c1613c6fe51d.png">

I believe this issue isn't about Xcode wrapper but about `libde265` itself. Can we find workaround to make this work?

**Comment by dreampiggy** [comment]
Maybe we should fire GitHub issue firstly to the author: https://github.com/strukturag/libde265/issues

Next, for workaroung, maybe we can now modify that file or provide a overlay, using `CocoaPods` or `SwiftPM` to do this...

Put the same header file and move the header search path (`-I`) beyond the original one, to make other files compiled with load this mock file firstly.

**Comment by dreampiggy** [comment]
Wait, did this file get loaded in on macOS only ? Maybe we can get a better workaround.

**Comment by esphynox** [comment]
Yes, this issue occurs only when building for macOS.

**Comment by esphynox** [comment]
Oh, I noticed someone opened issue in `libde265` - https://github.com/strukturag/libde265/issues/308

**Comment by esphynox** [comment]
I think I found way to build correct fat framework without modifying `libde265` itself. Will add PR soon.

**Comment by esphynox** [comment]
Hi there. I currently came up with two working ideas.

1. Remove all `sse` files from building. Its kinda easy and requires a little modification of `.xcodeproj` file, but I'm not sure how it will affect performance on x86 processors.
2. Have separate targets for x86 and Arm processor. This approach will require more work, since we will need to build those two libraries separately and merge them via some script that will perform `lipo` operation.

Maybe you can clarify for me what will exactly happen if I will remove `sse.h` includes from x86 library?

**Comment by esphynox** [comment]
Created PR, @dreampiggy

**Comment by dreampiggy** [comment]
Hi.
Recently I'm busying in daily work and may have no enough time for open-source project. I'll have a check for small changes PR soon.
For large refactory or features,  please try to summerize the idea and core changes, and I may check back in weekend.

**Comment by dreampiggy** [comment]
Actually... The raw Xcodeproj for Carthage may not get long time maintained...Beucase the reason for this repo was for CocoaPods && SwiftPM. Carthage is deprecated..

Anyway, I'll release a new path version firstly.
